### ISSUE TITLE
how do you find out what instruments have unilemmas? 

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbankr#16]
seems like we need a column `has_unilemmas` in instruments like `has_grammar`? otherwise, what's the preferred call to find out if an instrument has them?

**Comment by mikabr** [comment]
this would need to get added in wordbank itself, `wordbankr` would preserve that column in `get_instruments()`

**Comment by mcfrank** [comment]
It would be great to have if someone wouldn't mind adding it?

Mike

**Comment by daniellekellier** [comment]
Since most of the instruments do not have 100% coverage with unilemmas, would it be more informative to just report the % of words covered under that instrument with `get_instruments`?

**Comment by daniellekellier** [comment]
Should be accessible via wordbankr. There is a pesky warning due to the field in wordbank being a DecimalField that has to be converted to R's numeric class. Apparently, it has to due with RMySQL and it won't go away. In the pull request #18, I wrote some code that suppresses that specific warning and would let through any other issue.
