### ISSUE TITLE
Sex column missing in data

### ISSUE THREAD

**Issue by samhforbes** [langcog/wordbankr#42]
As in the title - no such column where there previously used to be. This is both on the app and on the child by item downloads from the website.

**Comment by mcfrank** [comment]
Thanks, can you provide a minimal working example?

We are running a tutorial today on Wordbank as it happens and have many
live sex-based analyses running.

Which dataset is this?

**Comment by samhforbes** [comment]
I've tested with French (French), Italian, and Japanese.

`library(wordbankr)`
`french_data <- wordbankr::get_instrument_data(language = 'French (French)', 
                                                   form = 'WG',
                                                   administration_info = T,
                                                   item_info = T)`

The column is also missing when downloading child-by-item from the website, when it wasn't previously. I can see the data does exist because when I plot split by gender and then download raw I can get Sex information from that.

**Comment by mcfrank** [comment]
Hi Sam, I think this may be a functionality change not a bug - we don't
provide demographics on instrument data (because the data transfer is too
large due to repeating the demographics 600+ times for every
administration). But it's easy to join this data back in, see our IASCL
tutorial from yesterday. :)

https://github.com/mcfrank/iascl-wordbank-tutorial/blob/2aafa5d46d57154817949b04da37dcb46ce98557/iascl-wordbank-tutorial-solutions.qmd#L294

**Comment by samhforbes** [comment]
Ah sorry I didn't see the function change! Yes confirm that solves the issue for the use cases we have over here. Thanks for the quick response (and sorry to miss IASCL).
